### PR TITLE
add picture tweeting capabilities.

### LINKED ISSUE #4: support toot -> tweet with pictures
When taking a toot with a picture, only the text is sent to Twitter, see pictures below as the tested example:

toot-spam
tweet-spam

### PR DESCRIPTION
**Pull request by mrkz**
when tooting with attached media (i.e: pictures), these were not
being processed to the mirror tweet posted. This commit introduces
the ability to post attached media from the toot into tweets.

Fixes #4

Signed-off-by: Simental Magana, Marcos <mrkzmrkz@gmail.com>

### CODE REVIEW

**Comment by mrkz** [comment]
At first, I tried to handle the image directly in-memory and avoid writing it into a file, but twitter API keeps asking for a filename or something alike, so I went ahead with this ugly way of doing it (i.e: write the file, use it, delete it).

**Comment by mrkz** [comment]
Following screenthots shown its working correctly :+1: 

Original Toot:
toot_spam
Mirrored Tweet:
tweet_spam

**Comment by bitkeks** [comment]
Hey @mrkz,
thanks for the work! Did not even know this bot works anymore :smile: 
I assumed that API changes in Mastodon and Twitter since the last release of this bot would have broken it..

You mentioned you tried to use in-memory files. Now you are writing files into the current working directory. Would it be okay for you to implement the tempfile module for this before the merge?

```python
import tempfile

# Create a temporary directory in system temp folder
tempdir = tempfile.TemporaryDirectory() 

# Skipping to relevant code:
    for media_file in media_attachments:
        media_id = media_file['id']
        media_type = media_file['type']
        media_url = media_file['url']
        media_content = urllib.request.urlopen(media_url)
        media_filename = tempdir + "/" + "{}.jpg".format(media_id)
        if media_type == 'image':
            with open(media_filename, 'wb') as f:
                f.write(media_content.read())
            tweet_media.append(media_filename)

# And later, instead of: 
# for media_file in tweet_media_delete:
#     os.remove(media_file)
# use the tempfile cleanup method:
tempdir.cleanup()

```
The reason to use a temporary directory is to not pollute the working dir with temporary files. And you don't have to use `os.remove()`.

**Comment by mrkz** [comment]
Hey again, sorry it took me forever to reply :sweat_smile: 

I really loved your approach using tmpdirs, thanks for the comment there.

I ended up creating the `TemporaryDirectory()` only when processing a toot with media, otherwise, we would just create/delete a tmpdir for every toot, either with or without media on it.

And using directly the `TemporaryDirectory` object leads to an exception, so I used `TemporaryDirectory.name` to get the actual tmpdir string to write the `*.jpg` files.

Thanks for taking the time to review this PR.

**Comment by mrkz** [comment]
friendly bump :smiley:

**Comment by mrkz** [comment]
hey, I created a dockerfile for this bot, I would really love to get it merged here too instead of having it somewhere else (i.e: https://github.com/mrkz/dockerfiles/tree/main/mas2tter) . maybe getting some merge would would be nice? :)

**Comment by mrkz** [comment]
I just noticed that I didn't add the configuration bits to the config.example.json. it's fixed now.

**Comment by bitkeks** [comment]
Very well.. thank you for your contribution ;)
Feel free to fork this repo, it will be archived soon.

**Pull request merged**
